Install missing symlinks, do not install test twice
dcantrell/bsdutils pull request #4
Opened 2021-06-12 15:48 UTC by q66

Also fix `test`'s install path missing a slash (which would result in it being installed in e.g. `/usr/localbin` instead of in
`/usr/local/bin`)

2021-06-12 16:22 UTC, dcantrell requested changes
Overall looks fine, but the meson scripts need to use the meson functions to determine the location of install-link.sh.

2021-06-12 16:22 UTC, dcantrell commented on src/ln/meson.build
> +    '../utils/install-link.sh', 'ln', 'link', get_option('bindir')
Avoid using relative paths in the meson files.  Use things like meson.source_root() or meson.current_source_root() to get the path to the file in question.  If it's a build artifact, you can use meson.build_root() or meson.current_build_root().

2021-06-12 16:22 UTC, dcantrell commented on src/ls/meson.build
> +    '../utils/install-link.sh', 'ls', 'dir', get_option('bindir')
Same as above.

2021-06-12 16:22 UTC, dcantrell commented on src/rm/meson.build
> +    '../utils/install-link.sh', 'rm', 'unlink', get_option('bindir')
Same.

2021-06-12 16:22 UTC, dcantrell commented on src/stat/meson.build
> +    '../utils/install-link.sh', 'stat', 'readlink', get_option('bindir')
Same.

2021-06-12 16:41 UTC, q66 commented on src/ln/meson.build
> +    '../utils/install-link.sh', 'ln', 'link', get_option('bindir')
good point

2021-06-12 18:06 UTC, q66 commented
removed the `dir` symlink as it's not entirely accurate (`dir` is `ls -C -b`) and probably doesn't belong in here anyway (it's not present in freebsd)

2021-06-13 18:33 UTC, dcantrell commented
Updates look good.  I am letting the CI run again since I merged your other PR.

I'm fine with the removal of 'dir'.  You're right, it's not in FreeBSD.  It's also not in OpenBSD which is what I originally based this project on years ago.  I've honestly never used the GNU 'dir' command anyway, so it's not a loss to me.  However I have a soft goal of trying to achieve parity with GNU coreutils as much as possible.  dir seems like a reasonable thing to exclude.

2021-06-13 18:34 UTC, dcantrell commented
Eh, the PR is against an older point in the tree.  Can you update this PR so it includes the working GHA CI workflow so the job can run?

2021-06-13 18:36 UTC, q66 commented
I will rebase once I get home.

By the way, I have started a project to complement bsdutils: https://github.com/chimera-linux/bsdutils-extra

2021-06-13 18:45 UTC, dcantrell commented
> I will rebase once I get home.

No rush.  I just got home myself and am catching up on things.  Was out of town for a bit.

> By the way, I have started a project to complement bsdutils: https://github.com/chimera-linux/bsdutils-extra

Nice.  For the *sum commands in GNU-world, I instead use the openssl dgst command.  The output looks different, but I don't mind.  The GNU commands do offer the -c option which is useful to check files you have against the digests you have.

2021-06-13 18:49 UTC, q66 commented
well, since I am building a general purpose system with this, this is largely for script compatibility, as well as so that people have their familiar commands - the intention is to implement all of the remaining commands coreutils offers over freebsd that make sense, while stuff that is offered in some form in freebsd itself should remain in bsdutils proper...

2021-06-14 15:14 UTC, dcantrell commented
> well, since I am building a general purpose system with this, this is largely for script compatibility, as well as so that people have their familiar commands - the intention is to implement all of the remaining commands coreutils offers over freebsd that make sense, while stuff that is offered in some form in freebsd itself should remain in bsdutils proper...

That makes sense.  For script compatibility, you could probably just do the *sum commands as scripts themselves that wrap openssl(1).  Together bsdutils + bsdutils-extra should provide a reasonable userspace environment.  I'm also not opposed to combining these two projects.  bsdutils already patches from FreeBSD anyway.  There's no reason it can't also carry the extras as part of the project.

2021-06-14 15:14 UTC, merged

2021-06-14 15:22 UTC, q66 commented
well, I don't see much of a reason to combine them, for the sake of cleanliness I'd probably keep bsdutils to only what came from freebsd plus patches, while the rest can be separate, and people can either opt for using both or just the base (none of the extra tools are necessary for every system)

I actually felt like implementing the rest in a higher level language (say, as a suite of python scripts) though in the end I opted for C anyway (makes for a smaller base system with an easier bootstrap path)